import type { Turno, Profesional, Servicio, Cliente } from "@/types";
import { addHours, setHours, setMinutes, startOfDay } from "date-fns";

const hoy = startOfDay(new Date());

export const mockProfesionales: Profesional[] = [
  {
    id: "p1",
    negocio_id: "n1",
    nombre: "María",
    apellido: "González",
    email: "maria@ejemplo.com",
    telefono: "+5491122334455",
    avatar_url: null,
    especialidad: "Colorista",
    activo: true,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
  },
  {
    id: "p2",
    negocio_id: "n1",
    nombre: "Carlos",
    apellido: "López",
    email: "carlos@ejemplo.com",
    telefono: "+5491155667788",
    avatar_url: null,
    especialidad: "Barbero",
    activo: true,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
  },
  {
    id: "p3",
    negocio_id: "n1",
    nombre: "Laura",
    apellido: "Martínez",
    email: "laura@ejemplo.com",
    telefono: "+5491188990011",
    avatar_url: null,
    especialidad: "Manicura",
    activo: true,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
  },
];

export const mockServicios: Servicio[] = [
  {
    id: "s1",
    negocio_id: "n1",
    nombre: "Corte de pelo",
    descripcion: "Corte y lavado",
    duracion_minutos: 45,
    precio: 3500,
    activo: true,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
  },
  {
    id: "s2",
    negocio_id: "n1",
    nombre: "Color completo",
    descripcion: "Tinte + lavado + secado",
    duracion_minutos: 120,
    precio: 12000,
    activo: true,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
  },
  {
    id: "s3",
    negocio_id: "n1",
    nombre: "Manicura",
    descripcion: "Manicura completa con esmalte",
    duracion_minutos: 60,
    precio: 4500,
    activo: true,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
  },
  {
    id: "s4",
    negocio_id: "n1",
    nombre: "Barba",
    descripcion: "Afeitado y arreglo de barba",
    duracion_minutos: 30,
    precio: 2800,
    activo: true,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
  },
];

export const mockClientes: Cliente[] = [
  {
    id: "c1",
    negocio_id: "n1",
    nombre: "Ana",
    apellido: "Pérez",
    telefono: "+5491100112233",
    email: "ana@email.com",
    notas: null,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
  },
  {
    id: "c2",
    negocio_id: "n1",
    nombre: "Juan",
    apellido: "García",
    telefono: "+5491133445566",
    email: null,
    notas: "Alérgico a ciertos tintes",
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
  },
  {
    id: "c3",
    negocio_id: "n1",
    nombre: "Valentina",
    apellido: "Romero",
    telefono: "+5491166778899",
    email: "valen@email.com",
    notas: null,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
  },
  {
    id: "c4",
    negocio_id: "n1",
    nombre: "Diego",
    apellido: "Torres",
    telefono: "+5491199001122",
    email: null,
    notas: null,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
  },
  {
    id: "c5",
    negocio_id: "n1",
    nombre: "Sofía",
    apellido: "Fernández",
    telefono: "+5491122334400",
    email: "sofia@email.com",
    notas: null,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
  },
];

function makeTime(hours: number, minutes: number = 0): string {
  return setMinutes(setHours(hoy, hours), minutes).toISOString();
}

export const mockTurnos: Turno[] = [
  {
    id: "t1",
    negocio_id: "n1",
    cliente_id: "c1",
    profesional_id: "p1",
    servicio_id: "s2",
    fecha_hora_inicio: makeTime(10, 0),
    fecha_hora_fin: makeTime(10, 30),
    estado: "completado",
    notas: null,
    precio_cobrado: 12000,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
    cliente: mockClientes[0],
    profesional: mockProfesionales[0],
    servicio: mockServicios[1],
  },
  {
    id: "t2",
    negocio_id: "n1",
    cliente_id: "c2",
    profesional_id: "p2",
    servicio_id: "s4",
    fecha_hora_inicio: makeTime(10, 0),
    fecha_hora_fin: makeTime(10, 30),
    estado: "completado",
    notas: null,
    precio_cobrado: 2800,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
    cliente: mockClientes[1],
    profesional: mockProfesionales[1],
    servicio: mockServicios[3],
  },
  {
    id: "t3",
    negocio_id: "n1",
    cliente_id: "c3",
    profesional_id: "p3",
    servicio_id: "s3",
    fecha_hora_inicio: makeTime(11, 0),
    fecha_hora_fin: makeTime(12, 0),
    estado: "confirmado",
    notas: null,
    precio_cobrado: null,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
    cliente: mockClientes[2],
    profesional: mockProfesionales[2],
    servicio: mockServicios[2],
  },
  {
    id: "t4",
    negocio_id: "n1",
    cliente_id: "c4",
    profesional_id: "p2",
    servicio_id: "s1",
    fecha_hora_inicio: makeTime(14, 0),
    fecha_hora_fin: makeTime(14, 45),
    estado: "confirmado",
    notas: null,
    precio_cobrado: null,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
    cliente: mockClientes[3],
    profesional: mockProfesionales[1],
    servicio: mockServicios[0],
  },
  {
    id: "t5",
    negocio_id: "n1",
    cliente_id: "c5",
    profesional_id: "p1",
    servicio_id: "s2",
    fecha_hora_inicio: makeTime(15, 30),
    fecha_hora_fin: makeTime(17, 30),
    estado: "pendiente",
    notas: "Primera visita",
    precio_cobrado: null,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
    cliente: mockClientes[4],
    profesional: mockProfesionales[0],
    servicio: mockServicios[1],
  },
  {
    id: "t6",
    negocio_id: "n1",
    cliente_id: "c1",
    profesional_id: "p3",
    servicio_id: "s3",
    fecha_hora_inicio: addHours(hoy, 18).toISOString(),
    fecha_hora_fin: addHours(hoy, 19).toISOString(),
    estado: "pendiente",
    notas: null,
    precio_cobrado: null,
    created_at: hoy.toISOString(),
    updated_at: hoy.toISOString(),
    cliente: mockClientes[0],
    profesional: mockProfesionales[2],
    servicio: mockServicios[2],
  },
];
